### PR TITLE
use stringifyRequest helper to compose relative pathes (fix #3)

### LINKED ISSUE #3: failed to use loader on windows
```
> rebem-starter-kit@0.0.0 start D:\wspace\starter-kit
> start-runner ./tasks.js "dev"

→ env: start
→ env: NODE_ENV = development
→ env: done

→ webpack dev: start
→ webpack dev: http://localhost:3000/webpack-dev-server/
→ webpack dev: done
Time: 1491ms
chunk    {0} bundle.js (main) 644 kB [rendered]

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'D:wspacestarter-kitsrccomponentsappindex.js' in D:\wspace\starter-kit\src
 @ ./src/index.js 5:53-113

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'D:wspacestarter-kit
ebem-theme-reseuildappstyles.css' in D:\wspace\starter-kit\src
 @ ./src/index.js 5:127-211

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'D:wspacestarter-kitsrc  heme-bootstrapappstyles.less' in D:\wspace\starter-kit\src
 @ ./src/index.js 5:213-281

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'D:wspacestarter-kitsrccomponentsappstyles.less' in D:\wspace\starter-kit\src
 @ ./src/index.js 5:283-346
webpack: bundle is now VALID.
```

### PR DESCRIPTION
**Pull request by Guria**
fixes #3

### CODE REVIEW

**Comment by Guria** [comment]
First of all, I have found that `somePath.split(path.sep).join('/')` or even `somePath.replace(/\\/g,'/')` are both acceptable solutions of windows path problem, because normal slashes are always used in `require` without cross-platform issues.
But I have checked a loader documentation and found recommendation to [avoid embedding absolute pathes](https://webpack.github.io/docs/how-to-write-a-loader.html#should-not-embed-absolute-paths) and [`stringifyRequest`](https://github.com/webpack/loader-utils/blob/master/index.js#L87-L101) utility method to get relative pathes. This method also [deals with windows pathes](https://github.com/webpack/loader-utils/blob/master/index.js#L96) as well.

But I had another WTF, because even after use of `stringifyRequest` webpack still wasn't able to find a module. I have to sleep to realize that utility returns already quoted string :facepalm:. I decided to strip it off, rather then editing `output.js` files with templates.

**Comment by deepsweet** [comment]
looks nice! but in my opinion editing `output.js` is more preferred way, could you please change it? I'll merge this asap.

**Comment by Guria** [comment]
@deepsweet do you mean: remove quotes in output.js instead off stripping in transform?

**Comment by Guria** [comment]
BTW, `stringifyRequest` use double-quotes. It means all expectation templates should be changed to expect double-quote in require statements too.
Also what about commits? Should I squash some of them?

**Comment by deepsweet** [comment]
yes, `output.js` should handle replaces like this.

**Comment by deepsweet** [comment]
also, there is another one in `lib/inject/output.js`

**Comment by Guria** [comment]
I saw both `output.js`. 
- Should I leave double quotes or replace it with single ones?
- Should I move `stringifyRequest` to output completely or only quote-replace part?

**Comment by deepsweet** [comment]
- replace double quotes (`output.js` may become external feature someday, so any output issues should be made there)
- the same, `stringifyRequest` is webpack only feature, so it should be placed in `output.js`

thanks!

**Comment by Guria** [comment]
It means need to pass loader context to `output.js` as well. are you sure with it? Currently `output.js` doesn't have loader context. it just manipulates some strings according to params.
It seems strange to me to "fix" input params in the same way in two different places.
In current solution output of `stringifyRequest` is just cleaned from quotes to be raw string and `output.js` is completely responsible to how it would look in output :).

**Comment by deepsweet** [comment]
I'm just thinking about splitting `layers-loader` into standalone `layers` module (to use it with browserify transform, for example) and tiny webpack loader... ok, let's leave it as is for now. please squash commits and I'll merge it.

**Comment by Guria** [comment]
squash all of them into one?

**Comment by deepsweet** [comment]
hm, maybe there is no need to squash them at all, LGTM. @mistadikay ?

**Comment by deepsweet** [comment]
(minor version bump?)

**Comment by Guria** [comment]
I think it just bugfix. there is no backward incompatibilities introduced, I am sure.

**Comment by mistadikay** [comment]
No need to squash!

**Pull request merged**
